package com.example.arcus.data.remote.languagemodel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A class that models responses generated by a large language model.
 */
@JsonClass(generateAdapter = true)
data class GeneratedTextResponse(
    val id: String,
    val created: Int,
    @Json(name = "choices") val generatedResponses: List<GeneratedResponse>
) {
    /**
     * A class that models a single generated response by a large language model.
     */
    @JsonClass(generateAdapter = true)
    data class GeneratedResponse(val message: MessageDTO)
}